### ISSUE TITLE
Issue with Mouse Event

### ISSUE THREAD

**Issue by Yogi09** [repeats/SimpleNativeHooks#4]
Sometimes it is giving below exception , how to solve this

![a](https://user-images.githubusercontent.com/25217822/59824577-2c831b80-934f-11e9-87a5-0a11c747a40f.png)
org.simplenativehooks.AbstractNativeHookEventProcessor processStdout
WARNING: Exception when processing stdout for Windows Hook. null
java.lang.NullPointerException
	at java.util.LinkedList$ListItr.next(LinkedList.java:893)
	at org.simplenativehooks.NativeHookGlobalEventPublisher.publishMouseEvent(NativeHookGlobalEventPublisher.java:56)
	at org.simplenativehooks.windows.GlobalWindowsEventOchestrator.processStdout(GlobalWindowsEventOchestrator.java:81)
	at org.simplenativehooks.AbstractNativeHookEventProcessor.processStdout(AbstractNativeHookEventProcessor.java:142)
	at org.simplenativehooks.AbstractNativeHookEventProcessor.access$000(AbstractNativeHookEventProcessor.java:13)
	at org.simplenativehooks.AbstractNativeHookEventProcessor$1.run(AbstractNativeHookEventProcessor.java:70)

**Comment by hptruong93** [comment]
Do you have steps to reproduce this?
Could you post your code here?

**Comment by Yogi09** [comment]
It produce some time not always, here is my code for starting and closing hook, code is same which is given in lib. using on windows 10.

public void closeHook() {
        try {
            NativeHookInitializer.of().stop();

        } catch (Exception ex) {
            System.out.println("Home Design " + ex);
        }
    }


public void keyboardPressed() {

        /* Extracting resources */
        try {
            BootStrapResources.extractResources();
        } catch (IOException e) {
            System.out.println("Cannot extract bootstrap resources.");
            e.printStackTrace();
            System.exit(2);
        }
        /* Initializing global hooks */
        NativeHookInitializer.of().start();

        /* Set up callbacks */
        NativeKeyHook key = NativeKeyHook.of();
        key.setKeyPressed(new Function<org.simplenativehooks.events.NativeKeyEvent, Boolean>() {
            @Override
            public Boolean apply(org.simplenativehooks.events.NativeKeyEvent d) {
                str_key_pressed = "Key Released: java "+d.getKey();
                arr_keyboard_pressed.add(str_key_pressed);
                mm = 1;
                return true;
            }
        });
        key.setKeyReleased(new Function<org.simplenativehooks.events.NativeKeyEvent, Boolean>() {
            @Override
            public Boolean apply(org.simplenativehooks.events.NativeKeyEvent d) {
                System.out.println("Key released: " + d.getKey());
                mm=1;
             
                return true;
            }
        });
        key.startListening();

        NativeMouseHook mouse = NativeMouseHook.of();
        mouse.setMousePressed(new Function<org.simplenativehooks.events.NativeMouseEvent, Boolean>() {
            @Override
            public Boolean apply(org.simplenativehooks.events.NativeMouseEvent d) {
                arr_mouse_moved.add(d.toString());
                mm = 1;
                return true;
            }
        });
        mouse.setMouseReleased(new Function<org.simplenativehooks.events.NativeMouseEvent, Boolean>() {
            @Override
            public Boolean apply(org.simplenativehooks.events.NativeMouseEvent d) {
                arr_mouse_moved.add(d.toString());
                mm = 1;
                return true;
            }
        });

        mouse.startListening();

    }
